### ISSUE TITLE
Data Discovery Engine

### ISSUE THREAD

**Issue by flaneuse** [biothings/metadataplus#1]
## What is the source's name
Data Discovery Engine

## What is the web address of the source

https://discovery.biothings.io/dataset

## Does this source require a user account login? Y/N

- [ ] Yes
- [x] No

## In short describe the importance of this source's addition
The Data Discovery Engine is a repository that allows users to register new datasets which don't have a home in other repos.  All datasets are based off of Schema.org's Dataset schema or other customized Dataset schemas, promoting findability, accessibilty, interoperability, and reusability.

**Comment by namespacestd0** [comment]
Available now at https://crawler.biothings.io/api/query?q=_index:indexed_discovery
